services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379" # Bind to localhost for security
    volumes:
      # This ensures your data survives if the container restarts
      - ./data:/data
    # This command tells Redis to save to disk every 60 seconds if at least 1 key changed
    command: redis-server --save 60 1 --loglevel warning
