services:
  mkdocs:
    container_name: mkdocs
    image: squidfunk/mkdocs-material
    # Added --livereload back
    command: serve --dev-addr=0.0.0.0:8000 --livereload
    # Added the environment block back
    environment:
      - WATCHDOG_FORCE_POLLING=true
    volumes:
      - /home/alex/kramer-homelab/docker/mkdocs/:/docs
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.rule=Host(`wiki.kramer.local`)"
      - "traefik.http.routers.wiki.entrypoints=web"
      - "traefik.http.services.wiki.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true