[global]
   workgroup = WORKGROUP
   security = user
   map to guest = Bad User
   server role = standalone server
   interfaces = lo enp4s0 vmbr0
   bind interfaces only = yes

[BigSamba]
   path = /mnt/bigsamba
   browsable = yes
   writable = yes
   guest ok = no
   valid users = smbuser
   create mask = 0777
   directory mask = 0777
   force user = smbuser