[infra]
# Since Ansible is running ON this machine, we tell it to connect locally
infra-services ansible_host=127.0.0.1 ansible_connection=local

[games]
linuxgame ansible_host=192.168.42.41 ansible_user=alex

[escapepod_nodes]
escapepod ansible_host=192.168.42.6 ansible_user=alex

[proxmox]
mothership ansible_host=192.168.42.5 ansible_user=root
holodeck ansible_host=192.168.42.8 ansible_user=root

[debian_vms:children]
# This creates a super-group specifically for your Debian/Mint environments
infra
games
escapepod_nodes